
CREATE DATABASE AULA_JAVA;
USE AULA_JAVA;

CREATE TABLE Cursos (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    carga_hora INT NOT NULL,
    area VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);
